organisms-header
SoutaYamasaki/souta-frontend-basic-last-assignment pull request #3
Opened 2023-01-01 13:59 UTC by SoutaYamasaki

## セルフチェック
- [o] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [o] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [o] 記述の重複はないか

http://localhost:6006/?path=/story/organisms-header--header

2023-01-04 09:15 UTC, MoAI522 commented
とりあえず今回のstorybook
https://6326a9158cfc223e7852740d-smumavbpve.chromatic.com/?path=/story/atoms-button--button

**レビュワーへ**
今後storybookを探すときはChromaticから直接このPRの最新に関連するビルドを開いて確認
chromaticのbuild一覧: https://www.chromatic.com/builds?appId=6326a9158cfc223e7852740d

2023-01-04 12:33 UTC, tomu-fujikawa reviewed
いい感じです！

修正点
・lgのときにバーガーアイコンをクリックしてもドロップダウンが開かないので修正お願いします！

![スクリーンショット (496)](https://user-images.githubusercontent.com/99815561/210554710-b3cf8e4b-99ba-4ff3-a69a-f11d68277c8a.png)
・「HOME」「CONCEPT」等の間の余白が40pxになるようにしてください（paddingやgap等）

![スクリーンショット (498)](https://user-images.githubusercontent.com/99815561/210555053-25a58189-f233-4add-a5ec-b7bceb8f9120.png)
・「HOME」「CONCEPT」等をホバーしたときに色が変わるようにしてください(色はgray_nobel)

![スクリーンショット (499)](https://user-images.githubusercontent.com/99815561/210555427-b5c9e0d6-8f23-4672-9ceb-09ea65f91514.png)
・「CONCEPT」のドロップダウンもホバーしたときに色が変わるようにしてください(色はorange_bistre)

![スクリーンショット (497)](https://user-images.githubusercontent.com/99815561/210555538-9dd8309d-ee39-4f3a-84b5-076c6cf3ac0c.png)
・写真のようにドロップダウンがピッタリ枠にくっつくようにしてください

2023-02-12 23:40 UTC, AyumuTaoka commented
こちら以下の画像のようにpaddingを調整することで修正できます
<img width="1440" alt="スクリーンショット 2023-02-13 8 37 34" src="https://user-images.githubusercontent.com/104242534/218344151-d4642af3-be32-4377-a36f-b904c29d2808.png">

2023-02-13 00:06 UTC, AyumuTaoka commented
xl以上の時にハンバーガーメニューが開かない問題ですが、自分は原因がよくわからないのでcollapseやidなどを少しずつ変更したりして何が原因で開かないのかを調べたり、要素の少ないheaderをもう一つ作ってどのプロパティが問題か探るのをお勧めします。

2023-04-13 15:20 UTC, higashiji2000 requested changes
![image](https://user-images.githubusercontent.com/83479175/231805704-1f6e3d58-6770-4d0a-be23-45efc1a2d04b.png)
検証ツールでみてみると、展開自体はできていることがわかります。

![image](https://user-images.githubusercontent.com/83479175/231806419-4befd57e-3f44-4909-aa90-8c4310dec643.png)
検証ツール上で背景色を黒にするとこんな感じになります。

検証ツールを使いながらlg以下のときのスタイルを整えていけば完成できると思います！

検証ツールの使い方についての教材：https://shinonome-inc.notion.site/chapter25-9bf1e0efdbbb4d7880e0d1c2dbb5e354

2023-04-18 04:20 UTC, higashiji2000 reviewed
![image](https://user-images.githubusercontent.com/83479175/232670230-280c8603-c6e1-4dc2-a6c6-91ef10a2e4ae.png)
![image](https://user-images.githubusercontent.com/83479175/232670336-3869cde6-4e0d-4057-ab2e-13984dde57c0.png)

上figma下storybookです。
paddingが少し違うっぽいので、figma通りの値になるようにしてください！

2023-04-18 04:20 UTC, higashiji2000 commented on src/components/organisms/header/header.scss
> +
```suggestion
  width: auto;

```
heightを固定値でもたせると伸縮しなくなるので、この指定をなくすといい感じの見た目になると思います！

![image](https://user-images.githubusercontent.com/83479175/232670016-fa87eb05-d026-496d-a856-fd3c74c9f4ba.png)

2023-04-18 04:20 UTC, higashiji2000 commented on src/components/organisms/header/header.scss
> +    }
![image](https://user-images.githubusercontent.com/83479175/232670084-22d75f2e-70a7-4962-9fdc-fdf9c1b685d9.png)
lg未満のときも色が変わってしまっているので、[こちら](https://demo.tcd-theme.com/tcd063/)を参考にlg未満は色が変わらないようにしてください！

2023-04-21 08:07 UTC, higashiji2000 requested changes
storybook
<img width="653" alt="image" src="https://user-images.githubusercontent.com/83479175/233579500-e234688e-4815-4fc5-aa73-8e7b4a562931.png">

figma
<img width="747" alt="image" src="https://user-images.githubusercontent.com/83479175/233579593-32f2c9c6-a7e7-45b0-a29b-046e646ce555.png">

文字間が見本に比べて狭くなっているので確認お願いします！

2023-04-21 08:07 UTC, higashiji2000 commented on src/components/organisms/header/header.scss
> +  }
```suggestion
  .dropdown-menu.concept-dropdown {
    padding: 0;
    border: none;
    margin: 0;
    &.collapsing {
      display: block;
    }
  }
```
こんな感じで `collapsing` に対して `display` を設定することで＋ボタンを押したあとのタイムラグがなくなると思うのでやってみてください

2023-04-21 08:07 UTC, higashiji2000 commented on src/components/organisms/header/header.scss
> +  }
```suggestion
```
この記述を消すことでロゴがちゃんと中央に寄ると思います！

2023-04-26 04:36 UTC, higashiji2000 approved these changes
LGTMです！📮

2023-04-28 04:07 UTC, merged